import turtle
# t = turtle.pen()
def turtles():
    turtle.forward(190)
    turtle.left(90)
    turtle.forward(190)
    turtle.left(90)
    turtle.forward(190)
    turtle.left(90)
    turtle.forward(190)
    turtle.forward(190)
    turtle.left(90)
    turtle.forward(190)
    turtle.left(90)
    turtle.forward(190)
    turtle.right(90)
    turtle.forward(190)
    turtle.clear() # همون جایی که هست میزاره باشه منتهی ردش رو پاک میکنه
    turtle.backward(200) # عقب گرد
    turtle.up() #برداشتن خودکار از روی صفحه
    turtle.right(90)
    turtle.forward(20)
    turtle.down() # گذاشتن خودکار روی صفحه
    turtle.left(90)
    turtle.forward(200)
    turtle.up() 
    turtle.right(90)
    turtle.forward(20)
    turtle.down()
    turtle.right(90)
    turtle.forward(200)
    turtle.left(135)
    turtle.forward(200)
    turtle.left(90)
    turtle.forward(200)
    turtle.left(90)
    turtle.forward(200)
    turtle.left(90)
    turtle.forward(400)
    turtle.right(90)
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(200)
    turtle.up()
    turtle.right(45)
    turtle.forward(140)
    turtle.down()
    turtle.right(90)
    turtle.forward(400)
    turtle.clear()
    for i in range(1,27):
        turtle.forward(100)
        turtle.left(95)
    turtle.done()
turtles() #Calling Function
# print("Test")
# Finish
